[build]
  publish = "."
  command = ""
  
[build.environment]
  NODE_VERSION = "18"

# HTML files will be served as-is
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# CSS files - shorter cache for updates
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

# JavaScript files - shorter cache for updates  
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA-like behavior (if needed)
[[redirects]]
  from = "/articles/*"
  to = "/articles/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
